#CLI:
#  TYPE: [SSH,TELNET] # SSH,TELNET
#  PORTS:
#    SSH: 22
#    TELNET: 53
LOGGING:
  LEVEL: DEBUG  # DEBUG/INFO
DEBUG_ENABLED: FALSE  # TRUE/FALSE

# Delay simulation
DELAY_MIN: 1
DELAY_MAX: 10

# Override existing mapping or not
OVERRIDE_MAPPING: FALSE